capi: add missing const-qualifier to __librashader__noop_*_filter_chain_get_param
The libra_*_filter_chain_t *chain parameter of the __librashader__noop_*_filter_chain_get_param
functions in the librashader_ld.h header require the const-qualifier after commit
https://github.com/SnowflakePowered/librashader/commit/c447e405831b692ff12d62fe1157041d4a2ad29a.

Otherwise compilation of consumers like the ares emulator fails with the following
error:

/usr/local/include/librashader/librashader_ld.h:1458:9: error: assigning to 'PFN_libra_gl_filter_chain_get_param' (aka '_libra_error *(*)(_filter_chain_gl *const *, const char *, float *)') from incompatible type 'libra_error_t (libra_gl_filter_chain_t *, const char *, float *)' (aka '_libra_error *(_filter_chain_gl **, const char *, float *)'): type mismatch at 1st parameter ('const libra_gl_filter_chain_t *' (aka '_filter_chain_gl *const *') vs 'libra_gl_filter_chain_t *' (aka '_filter_chain_gl **'))
 1458 |         __librashader__noop_gl_filter_chain_get_param;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~